language: node_js
sudo: required
dist: trusty
cache:
  directories:
    - node_modules
services:
  - docker
node_js:
  - "8"
before_install:
  - docker run --name mysql -d -e MYSQL_ROOT_PASSWORD=password -p 13306:3306 mariadb:10.4.4
  - docker ps -a
  - npm install
after_script:
  - codeclimate-test-reporter < reports/lcov.info
  - docker rm -fv mysql
