language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "6.2.1"
before_install:
  - $CXX --version
  - npm install
after_script:
  - codeclimate-test-reporter < reports/lcov.info
